Roguelike. Боевая система.
skychik/roguelike pull request #3
Opened 2021-05-03 07:04 UTC by zhvkgj

2021-05-14 20:59 UTC, aleksZubakov requested changes
В целом, более-менее ок, 7 баллов

2021-05-14 20:59 UTC, aleksZubakov commented on game-client/src/main/kotlin/ru/ifmo/sd/stuff/GUI.kt
> +//        mapTextPane.select(0, 0)
Давайте еще раз

> Не должно быть закомментированного кода

2021-05-14 20:59 UTC, aleksZubakov commented on game-server/src/main/kotlin/ru/ifmo/sd/world/events/EventsHandler.kt
> +        val playerPos = maze.freePos.random()
Помучаетесь немного при переходе на мультиплеер, но ок

2021-05-14 20:59 UTC, aleksZubakov commented on game-server/src/main/kotlin/ru/ifmo/sd/world/events/EventsHandler.kt
> +        gameLevel = null
Это не похоже на рестарт, это похоже на `stop` или `close`

2021-05-14 20:59 UTC, aleksZubakov commented on game-server/src/main/kotlin/ru/ifmo/sd/world/events/InteractionExecutorImpl.kt
> +        val unitsHealthStorage = EventsHandler.gameLevel!!.unitsHealthStorage
Опасное на падение место, т.к. `gameLevel` не всегда не null.

2021-05-14 20:59 UTC, aleksZubakov commented on game-server/src/main/kotlin/ru/ifmo/sd/world/npc/strategy/Passive.kt
> +        val directionsToMove = listOf(
Этот список не меняется, лучше его не создавать при каждом вызове

2021-05-14 20:59 UTC, aleksZubakov commented on game-server/src/main/kotlin/ru/ifmo/sd/world/events/EventsHandler.kt
> +    private fun moveToOccupiedPos(playerPos: Position, targetPos: Position, gameLevel: GameLevel): GameMove {
Эти два метода точно нельзя обобщить?

2021-05-24 19:12 UTC, zhvkgj commented on game-server/src/main/kotlin/ru/ifmo/sd/world/npc/strategy/Passive.kt
> +        val directionsToMove = listOf(
Согласен, поправил.

2021-05-25 10:46 UTC, zhvkgj commented on game-server/src/main/kotlin/ru/ifmo/sd/world/npc/strategy/Passive.kt
> +        val directionsToMove = listOf(
Согласен, поправил здесь и в других стратегиях.

2021-05-25 10:50 UTC, zhvkgj commented on game-server/src/main/kotlin/ru/ifmo/sd/world/events/InteractionExecutorImpl.kt
> +        val unitsHealthStorage = EventsHandler.gameLevel!!.unitsHealthStorage
Здесь подразумевается, что при нормальной работе программы никаких взаимодействий от клиента не может прилететь, если gameLevel null. Видимо лучше тут явно кидать исключение или что-то подобное для сигнализирования некоррекности работы программы.

2021-05-25 10:53 UTC, zhvkgj commented on game-server/src/main/kotlin/ru/ifmo/sd/world/events/EventsHandler.kt
> +        val playerPos = maze.freePos.random()
Конечно при реализации мультиплеера выдача позиции будет происходить немного по-другому.

2021-05-31 23:26 UTC, aleksZubakov commented
Засчитываю

2021-05-31 23:26 UTC, closed without merging